-- Migración: Añadir "Internacional" como departamento y todos los países del mundo como municipios
-- Esto permite seleccionar países extranjeros en los campos de lugar de las entrevistas.

DO $$
DECLARE
    v_id_internacional INTEGER;
BEGIN
    -- Verificar si ya existe "Internacional"
    SELECT id_geo INTO v_id_internacional
    FROM catalogos.geo
    WHERE nivel = 2 AND descripcion = 'Internacional'
    LIMIT 1;

    -- Si no existe, insertarlo
    IF v_id_internacional IS NULL THEN
        INSERT INTO catalogos.geo (id_padre, nivel, id_tipo, codigo, descripcion, lat, lon, codigo_2)
        VALUES (NULL, 2, NULL, 'INT', 'Internacional', NULL, NULL, NULL)
        RETURNING id_geo INTO v_id_internacional;
    END IF;

    -- Insertar países solo si no existen ya (verificar por código ISO)
    -- Se usa ON CONFLICT solo si no hay constraint, así que verificamos con NOT EXISTS
    INSERT INTO catalogos.geo (id_padre, nivel, id_tipo, codigo, descripcion, lat, lon, codigo_2)
    SELECT v_id_internacional, 3, NULL, codigo, descripcion, NULL, NULL, NULL
    FROM (VALUES
        ('AF', 'Afganistan'),
        ('AL', 'Albania'),
        ('DE', 'Alemania'),
        ('AD', 'Andorra'),
        ('AO', 'Angola'),
        ('AG', 'Antigua y Barbuda'),
        ('SA', 'Arabia Saudita'),
        ('DZ', 'Argelia'),
        ('AR', 'Argentina'),
        ('AM', 'Armenia'),
        ('AU', 'Australia'),
        ('AT', 'Austria'),
        ('AZ', 'Azerbaiyan'),
        ('BS', 'Bahamas'),
        ('BD', 'Bangladesh'),
        ('BB', 'Barbados'),
        ('BH', 'Barein'),
        ('BE', 'Belgica'),
        ('BZ', 'Belice'),
        ('BJ', 'Benin'),
        ('BY', 'Bielorrusia'),
        ('MM', 'Birmania (Myanmar)'),
        ('BO', 'Bolivia'),
        ('BA', 'Bosnia y Herzegovina'),
        ('BW', 'Botsuana'),
        ('BR', 'Brasil'),
        ('BN', 'Brunei'),
        ('BG', 'Bulgaria'),
        ('BF', 'Burkina Faso'),
        ('BI', 'Burundi'),
        ('BT', 'Butan'),
        ('CV', 'Cabo Verde'),
        ('KH', 'Camboya'),
        ('CM', 'Camerun'),
        ('CA', 'Canada'),
        ('QA', 'Catar'),
        ('TD', 'Chad'),
        ('CL', 'Chile'),
        ('CN', 'China'),
        ('CY', 'Chipre'),
        ('CO', 'Colombia'),
        ('KM', 'Comoras'),
        ('KP', 'Corea del Norte'),
        ('KR', 'Corea del Sur'),
        ('CI', 'Costa de Marfil'),
        ('CR', 'Costa Rica'),
        ('HR', 'Croacia'),
        ('CU', 'Cuba'),
        ('DK', 'Dinamarca'),
        ('DM', 'Dominica'),
        ('EC', 'Ecuador'),
        ('EG', 'Egipto'),
        ('SV', 'El Salvador'),
        ('AE', 'Emiratos Arabes Unidos'),
        ('ER', 'Eritrea'),
        ('SK', 'Eslovaquia'),
        ('SI', 'Eslovenia'),
        ('ES', 'Espana'),
        ('US', 'Estados Unidos'),
        ('EE', 'Estonia'),
        ('SZ', 'Esuatini'),
        ('ET', 'Etiopia'),
        ('PH', 'Filipinas'),
        ('FI', 'Finlandia'),
        ('FJ', 'Fiyi'),
        ('FR', 'Francia'),
        ('GA', 'Gabon'),
        ('GM', 'Gambia'),
        ('GE', 'Georgia'),
        ('GH', 'Ghana'),
        ('GD', 'Granada'),
        ('GR', 'Grecia'),
        ('GT', 'Guatemala'),
        ('GN', 'Guinea'),
        ('GQ', 'Guinea Ecuatorial'),
        ('GW', 'Guinea-Bisau'),
        ('GY', 'Guyana'),
        ('HT', 'Haiti'),
        ('HN', 'Honduras'),
        ('HU', 'Hungria'),
        ('IN', 'India'),
        ('ID', 'Indonesia'),
        ('IQ', 'Irak'),
        ('IR', 'Iran'),
        ('IE', 'Irlanda'),
        ('IS', 'Islandia'),
        ('IL', 'Israel'),
        ('IT', 'Italia'),
        ('JM', 'Jamaica'),
        ('JP', 'Japon'),
        ('JO', 'Jordania'),
        ('KZ', 'Kazajistan'),
        ('KE', 'Kenia'),
        ('KG', 'Kirguistan'),
        ('KI', 'Kiribati'),
        ('KW', 'Kuwait'),
        ('LA', 'Laos'),
        ('LS', 'Lesoto'),
        ('LV', 'Letonia'),
        ('LB', 'Libano'),
        ('LR', 'Liberia'),
        ('LY', 'Libia'),
        ('LI', 'Liechtenstein'),
        ('LT', 'Lituania'),
        ('LU', 'Luxemburgo'),
        ('MK', 'Macedonia del Norte'),
        ('MG', 'Madagascar'),
        ('MY', 'Malasia'),
        ('MW', 'Malaui'),
        ('MV', 'Maldivas'),
        ('ML', 'Mali'),
        ('MT', 'Malta'),
        ('MA', 'Marruecos'),
        ('MH', 'Islas Marshall'),
        ('MU', 'Mauricio'),
        ('MR', 'Mauritania'),
        ('MX', 'Mexico'),
        ('FM', 'Micronesia'),
        ('MD', 'Moldavia'),
        ('MC', 'Monaco'),
        ('MN', 'Mongolia'),
        ('ME', 'Montenegro'),
        ('MZ', 'Mozambique'),
        ('NA', 'Namibia'),
        ('NR', 'Nauru'),
        ('NP', 'Nepal'),
        ('NI', 'Nicaragua'),
        ('NE', 'Niger'),
        ('NG', 'Nigeria'),
        ('NO', 'Noruega'),
        ('NZ', 'Nueva Zelanda'),
        ('OM', 'Oman'),
        ('NL', 'Paises Bajos'),
        ('PK', 'Pakistan'),
        ('PW', 'Palaos'),
        ('PS', 'Palestina'),
        ('PA', 'Panama'),
        ('PG', 'Papua Nueva Guinea'),
        ('PY', 'Paraguay'),
        ('PE', 'Peru'),
        ('PL', 'Polonia'),
        ('PT', 'Portugal'),
        ('GB', 'Reino Unido'),
        ('CF', 'Republica Centroafricana'),
        ('CZ', 'Republica Checa'),
        ('CG', 'Republica del Congo'),
        ('CD', 'Republica Democratica del Congo'),
        ('DO', 'Republica Dominicana'),
        ('RW', 'Ruanda'),
        ('RO', 'Rumania'),
        ('RU', 'Rusia'),
        ('WS', 'Samoa'),
        ('KN', 'San Cristobal y Nieves'),
        ('SM', 'San Marino'),
        ('VC', 'San Vicente y las Granadinas'),
        ('LC', 'Santa Lucia'),
        ('ST', 'Santo Tome y Principe'),
        ('SN', 'Senegal'),
        ('RS', 'Serbia'),
        ('SC', 'Seychelles'),
        ('SL', 'Sierra Leona'),
        ('SG', 'Singapur'),
        ('SY', 'Siria'),
        ('SO', 'Somalia'),
        ('LK', 'Sri Lanka'),
        ('ZA', 'Sudafrica'),
        ('SD', 'Sudan'),
        ('SS', 'Sudan del Sur'),
        ('SE', 'Suecia'),
        ('CH', 'Suiza'),
        ('SR', 'Surinam'),
        ('TH', 'Tailandia'),
        ('TW', 'Taiwan'),
        ('TZ', 'Tanzania'),
        ('TJ', 'Tayikistan'),
        ('TL', 'Timor Oriental'),
        ('TG', 'Togo'),
        ('TO', 'Tonga'),
        ('TT', 'Trinidad y Tobago'),
        ('TN', 'Tunez'),
        ('TM', 'Turkmenistan'),
        ('TR', 'Turquia'),
        ('TV', 'Tuvalu'),
        ('UA', 'Ucrania'),
        ('UG', 'Uganda'),
        ('UY', 'Uruguay'),
        ('UZ', 'Uzbekistan'),
        ('VU', 'Vanuatu'),
        ('VA', 'Vaticano'),
        ('VE', 'Venezuela'),
        ('VN', 'Vietnam'),
        ('YE', 'Yemen'),
        ('DJ', 'Yibuti'),
        ('ZM', 'Zambia'),
        ('ZW', 'Zimbabue')
    ) AS paises(codigo, descripcion)
    WHERE NOT EXISTS (
        SELECT 1 FROM catalogos.geo g
        WHERE g.id_padre = v_id_internacional
        AND g.codigo = paises.codigo
        AND g.nivel = 3
    );

    RAISE NOTICE 'Internacional id_geo: %, paises insertados correctamente.', v_id_internacional;
END $$;
