[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisord.log
logfile_maxbytes=10MB
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-worker]
command=php /var/www/artisan queue:work --sleep=3 --tries=2 --timeout=3600 --max-time=3600
directory=/var/www
autostart=true
autorestart=true
priority=2
stopwaitsecs=3600
stdout_logfile=/var/www/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/www/storage/logs/queue-worker-error.log
stderr_logfile_maxbytes=5MB
